#!/bin/bash
if [[ $# -eq 0 ]] ; then
	echo "need to provide file name"
	exit 1
fi

if [ "$1" == "min" ] ; then
    if [[ $# -eq 1 ]] ; then
        echo "need to provide file name"
        exit 1
    fi
    cp C:/Users/jerry/bin/template_min.cpp $PWD/$2
elif [ "$1" == "base" ] ; then
    if [[ $# -eq 1 ]] ; then
        echo "need to provide file name"
        exit 1
    fi
    cp C:/Users/jerry/bin/template_base.cpp $PWD/$2
else
    cp C:/Users/jerry/bin/template.cpp $PWD/$1
fi
